# Generated by Django 4.2 on 2024-09-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdVenta', models.CharField(max_length=100)),
                ('IdProducto', models.CharField(max_length=100)),
                ('PrecioVenta', models.FloatField()),
                ('Cantidad', models.CharField(max_length=100)),
                ('SubTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'detalles_ventas',
            },
        ),
    ]
