# Generated by Django 4.2.16 on 2024-10-04 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_idusuario_venta_usuario'),
        ('producto', '0001_initial'),
        ('detalle_ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='IdProducto',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='IdVenta',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producto.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ventas.venta', verbose_name='Codigo Venta'),
            preserve_default=False,
        ),
    ]
