# Generated by Django 4.2.16 on 2024-10-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_ventas', '0002_remove_detalle_venta_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={'verbose_name_plural': 'Detalles de Ventas'},
        ),
    ]
