# Generated by Django 4.2 on 2024-09-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('RUC', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Logo', models.BinaryField()),
            ],
            options={
                'verbose_name_plural': 'Negocios',
            },
        ),
    ]
