# Generated by Django 4.2.16 on 2024-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='Logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
