# Generated by Django 4.2 on 2024-09-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.IntegerField()),
                ('TipoDocumento', models.CharField(max_length=100)),
                ('NumeroDocumento', models.IntegerField()),
                ('DocumentoCliente', models.IntegerField()),
                ('NombreCliente', models.CharField(max_length=100)),
                ('MontoPago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoCambio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecharegistro', models.DateField()),
                ('TipoPago', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
