# Generated by Django 4.2.16 on 2024-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='TipoPago',
            field=models.CharField(max_length=100),
        ),
    ]
