# Generated by Django 4.2.16 on 2024-11-05 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
        ('ventas', '0003_remove_venta_idusuario_venta_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='DocumentoCliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Fecharegistro',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='MontoCambio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='MontoPago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='MontoTotal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='NombreCliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='NumeroDocumento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='TipoDocumento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='TipoPago',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_cambio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto de Cambio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Monto de Pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Monto Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Número de Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(default=1, max_length=50, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CRÉDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default=1, max_length=20, verbose_name='Tipo de Pago'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_documento'], name='ventas_vent_numero__da1312_idx'),
        ),
        migrations.AddField(
            model_name='detallesventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detallesventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AddIndex(
            model_name='detallesventa',
            index=models.Index(fields=['venta', 'producto'], name='ventas_deta_venta_i_cb7ae6_idx'),
        ),
    ]
