# Generated by Django 4.2.16 on 2024-11-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
        ('ventas', '0004_detallesventa_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallesventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallesventa',
            name='venta',
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_numero__da1312_idx',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_cambio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='DetallesVenta',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='ventas.venta'),
        ),
    ]
