# Generated by Django 4.2.16 on 2024-10-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Stock', models.IntegerField()),
                ('PrecioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.BooleanField(default=False)),
                ('FechaRegistro', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
