# Generated by Django 4.2.16 on 2024-10-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('compras', '0002_remove_compra_idusuario_compra_usuario'),
        ('detalle_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compra',
            name='IdCompra',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='IdProducto',
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='compras.compra', verbose_name='Codigo Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producto.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
