# Generated by Django 4.2.16 on 2024-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_compras', '0002_remove_detalle_compra_idcompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='PrecioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
