# Generated by Django 4.2.16 on 2024-10-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_compras', '0003_alter_detalle_compra_precioventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_compra',
            options={'verbose_name_plural': 'Detalles de Compras'},
        ),
    ]
