# Generated by Django 4.2.16 on 2024-10-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_rename_descripcion_rol_descripcion_and_more'),
        ('permiso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='IdROl',
        ),
        migrations.AddField(
            model_name='permiso',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rol.rol', verbose_name='Rol'),
            preserve_default=False,
        ),
    ]
