# Generated by Django 4.2 on 2024-09-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.IntegerField()),
                ('RazonSocial', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Estado', models.BinaryField()),
                ('FechaRegistro', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
