# Generated by Django 4.2.16 on 2024-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Estado',
            field=models.BooleanField(default=False),
        ),
    ]
