# Generated by Django 4.2 on 2024-09-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='fechaCreacion',
            new_name='FechaRegistro',
        ),
    ]
